package mypack;
// Generated Sep 28, 2020 9:52:28 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeptId generated by hbm2java
 */
@Embeddable
public class DeptId implements java.io.Serializable {

	private String name;
	private String location;

	public DeptId() {
	}

	public DeptId(String name, String location) {
		this.name = name;
		this.location = location;
	}

	@Column(name = "Name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Location", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptId))
			return false;
		DeptId castOther = (DeptId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		return result;
	}

}
